# Generated by Django 4.1 on 2022-08-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mark', models.IntegerField()),
                ('stu_location', models.CharField(max_length=25)),
            ],
        ),
    ]
